"""
Path D — Step 2: CLIP frame prefilter (NVIDIA CUDA or Intel GPU via OpenVINO).

A reusable scorer that ranks video frames by how well they match a text query,
using CLIP on the GPU (~3-7 ms/frame). It is meant to run as a *prefilter*: scan
the whole video cheaply, keep the top-K candidate timestamps, and let the slow
uncensored VLM confirm only those.

Two backends, same weights and the same output fields, picked automatically:

  - **torch/CUDA** on an NVIDIA GPU. OpenVINO has no NVIDIA plugin, so on those
    machines the OpenVINO path below silently lands on the CPU — an order of
    magnitude slower. Hence this backend.
  - **OpenVINO** on an Intel GPU (and as the CPU fallback everywhere).

Embeddings from the two agree to well under the fp16 the index stores, so a
cache built on one machine stays valid on the other.

CLIP has no safety filter and never refuses — it only computes image<->text
similarity — which is exactly why it works for content the VLM then confirms.

Standalone usage (test on a real video before any app integration):

    python -m llm.clip_prefilter --video "D:\\movies\\clip.mp4" \
        --query "your real target wording" --interval 1.0 --topk 30

Watch whether the top-K timestamps actually land on the moments you expect.
If they do, we wire this into the visual-search worker. If base CLIP is too
weak for your target, change MODEL_ID to a domain-tuned CLIP — same code path.

Requires:  pip install transformers pillow opencv-python numpy
           ...plus one backend:
             NVIDIA — a CUDA torch build (pytorch.org); optimum is not needed
             Intel/CPU — pip install "optimum[openvino]" optimum-intel

`python -m tools.check_clip_device` reports which backend a machine resolves to,
proves it agrees with the CPU, and benchmarks it.
"""
from __future__ import annotations

import os
import sys
import time
from typing import Optional


# clip-vit-base-patch32 is general-purpose: fast and proven on the Arc GPU.
# Swap for a domain-tuned CLIP later if ranking recall is insufficient.
MODEL_ID = "openai/clip-vit-base-patch32"

# Directory name of the pre-converted OpenVINO IR (model + processor) shipped
# under models/. Converting the HF PyTorch model at runtime (export=True) traces
# its source via inspect.getsource, which raises "could not get source code" in a
# frozen exe where .py sources aren't bundled. So a packaged build must load an
# already-exported IR instead. Generated by tools/export_clip_ov.py.
#
# The IR alone is not enough: merely importing OVModelForZeroShotImageClassification
# runs transformers' docstring decorators, which call inspect.getsource on the
# optimum-defined forward methods. So optimum must ship WITH its .py sources — see
# packaging/pyinstaller-hooks/hook-optimum.py (module_collection_mode "pyz+py").
# (transformers already gets the same treatment from its bundled contrib hook.)
BUNDLED_OV_DIRNAME = "clip-vit-base-patch32-ov"


def _ov_dir_candidates() -> list[str]:
    """Every place the pre-converted IR might live, most-specific first.

    Self-contained (no dependency on modules.system.app_paths, which may not import
    cleanly from a lazily-imported module inside a frozen exe). Covers:
      - user-dropped override next to the exe / in the project root
      - the PyInstaller bundle dir (sys._MEIPASS)
      - running from source (the repo's models/ dir)
    """
    rel = os.path.join("models", BUNDLED_OV_DIRNAME)
    bases: list[str] = []
    if getattr(sys, "frozen", False):
        bases.append(os.path.dirname(sys.executable))          # override next to exe
        # Downloaded by the app into the per-user folder when the exe's folder
        # is read-only (modules/packs/pack_manager.per_user_dir, same rule).
        if sys.platform == "win32":
            user_base = os.environ.get("LOCALAPPDATA") or os.path.expanduser(r"~\AppData\Local")
        elif sys.platform == "darwin":
            user_base = os.path.expanduser("~/Library/Application Support")
        else:
            user_base = os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
        bases.append(os.path.join(user_base, "VideoHighlighter"))
        meipass = getattr(sys, "_MEIPASS", None)
        if meipass:
            bases.append(meipass)                              # bundled resources
    # repo root: llm/clip_prefilter.py -> parent of llm/
    bases.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    return [os.path.join(b, rel) for b in bases]


def _bundled_ov_dir() -> Optional[str]:
    """Path to the pre-converted OpenVINO CLIP dir if it ships with the app,
    else None (dev fallback to runtime export). Honours a user-dropped copy."""
    for path in _ov_dir_candidates():
        # A valid OV export has an openvino_model.xml at its root.
        if os.path.isfile(os.path.join(path, "openvino_model.xml")):
            return path
    return None


# ---------------------------------------------------------------------------
# Backend selection
#
# Deliberately a local probe rather than modules.system.device_utils: this module is
# lazily imported (sometimes inside a frozen exe) and stays self-contained for
# the same reason _ov_dir_candidates does. detect_best_device() would also drag
# in an OpenVINO Core probe and its logging just to answer one bool.
# ---------------------------------------------------------------------------

# Device strings that mean "whichever GPU this machine actually has". "GPU" is
# included because every existing caller passes it to mean exactly that, and
# because OpenVINO's "GPU" (= Intel) is a dead end on an NVIDIA box.
_AUTO_DEVICES = ("AUTO", "GPU")


def cuda_device() -> Optional[str]:
    """The torch device string for a usable NVIDIA GPU, else None.

    Never raises: a torch without CUDA compiled in, or a driver mismatch, means
    "no CUDA" rather than a broken search.
    """
    try:
        import torch
    except Exception:
        return None
    try:
        # A card newer than this torch build is "available" and still cannot
        # run a kernel; see modules/system/cuda_check.py.
        from modules.system.cuda_check import cuda_usable
        return "cuda:0" if cuda_usable(torch) else None
    except ImportError:
        pass
    try:
        if torch.cuda.is_available() and torch.cuda.device_count() > 0:
            return "cuda:0"
    except Exception as e:  # noqa: BLE001 — a probe must never break the caller
        print(f"⚠️  CLIP: CUDA probe failed ({type(e).__name__}: {e})")
    return None


def directml_device() -> Optional[str]:
    """The torch device string for a usable DirectML GPU, else None.

    One of two places this module reaches into `modules/` (the other is
    `cuda_device`, on the same terms) — deliberately, and it does not break the
    self-containment the block above describes: `modules.system.directml_device`
    imports nothing but `os` and `typing` at module scope, so it costs the same
    as the local probe it would otherwise be. The
    reason not to inline it is that DirectML has genuine footguns (the backend
    name changed between releases; the import is what registers the backend at
    all) and a copy of that reasoning per module is a copy that goes stale.
    """
    try:
        from modules.system import directml_device as dml
    except Exception:  # noqa: BLE001 — absent module means "no DirectML"
        return None
    try:
        return dml.device_string()
    except Exception as e:  # noqa: BLE001 — a probe must never break the caller
        print(f"⚠️  CLIP: DirectML probe failed ({type(e).__name__}: {e})")
        return None


def _is_directml(device: str) -> bool:
    try:
        from modules.system import directml_device as dml
        return dml.is_directml(device)
    except Exception:  # noqa: BLE001
        return False


def _device_name(device: str) -> str:
    """The GPU's marketing name for the log, or the bare device string. Cosmetic
    only — never let a failed lookup here cost us the GPU."""
    if _is_directml(device):
        # torch.cuda.get_device_name() raises on a DirectML device, and the
        # name matters more here than on CUDA: DirectML enumerates the
        # integrated GPU and the software renderer alongside the real card.
        try:
            from modules.system import directml_device as dml
            return dml.probe().name() or device
        except Exception:  # noqa: BLE001
            return device
    try:
        import torch

        return torch.cuda.get_device_name(device)
    except Exception:  # noqa: BLE001
        return device


def resolve_device(requested: str) -> tuple[str, str]:
    """Map a requested device onto (backend, device).

    backend is "torch" or "openvino"; device is that backend's own device string.

        "AUTO"/"GPU" -> CUDA, else DirectML (AMD), else OpenVINO GPU (Intel),
                        else CPU
        "CUDA"/"cuda:N" -> torch CUDA, falling back to OpenVINO if absent
        "DML"/"directml"/"privateuseone:N" -> torch DirectML, falling back to
                        OpenVINO if this machine cannot provide one
        anything else ("CPU", "GPU.1", "NPU", ...) -> OpenVINO, passed through

    DirectML is tried after CUDA and before OpenVINO because the OpenVINO GPU
    plugin is Intel-only: on an AMD box "openvino", "GPU" silently means the
    CPU, so DirectML is competing with the processor there, not with a GPU. On
    an Intel box the order never matters, since CUDA is absent and DirectML is
    only reached if `modules.system.directml_device` says yes — and on stock installs
    torch-directml is not there to say anything.
    """
    req = (requested or "AUTO").strip()

    if req.upper() in _AUTO_DEVICES:
        dev = cuda_device()
        if dev:
            return "torch", dev
        dev = directml_device()
        if dev:
            return "torch", dev
        # No NVIDIA and no DirectML: hand OpenVINO the Intel GPU. load() drops
        # to CPU if the plugin won't take it, so "GPU" stays safe on a machine
        # with neither.
        return "openvino", "GPU"

    if _is_directml(req):
        dev = directml_device()
        if dev:
            return "torch", dev
        print(f"⚠️  CLIP: {req!r} requested but DirectML is unavailable; "
              f"using OpenVINO.")
        return "openvino", "GPU"

    if req.lower().startswith("cuda"):
        dev = cuda_device()
        if dev:
            # Honour an explicit ordinal ("cuda:1"); bare "cuda" -> cuda:0.
            return "torch", req.lower() if ":" in req else dev
        print(f"⚠️  CLIP: {req!r} requested but no CUDA device is available; "
              f"using OpenVINO.")
        return "openvino", "GPU"

    return "openvino", req


def to_numpy(tensor):
    """Tensor -> numpy, from either backend.

    The CUDA backend's outputs live in GPU memory, where .numpy() raises; the
    .cpu() hop is a no-op on the OpenVINO backend's already-CPU tensors.
    """
    return tensor.detach().cpu().numpy()


class ClipFramePrefilter:
    """Score BGR frames (OpenCV format) against a text query via CLIP,
    on NVIDIA (torch/CUDA) or Intel/CPU (OpenVINO)."""

    # Generic negatives so the positive prompt gets a calibrated softmax score
    # rather than a raw, hard-to-threshold cosine similarity.
    DEFAULT_NEGATIVES = (
        "an unrelated scene",
        "a neutral background",
        "something else entirely",
    )

    def __init__(self, model_id: str = MODEL_ID, device: str = "AUTO"):
        self.model_id = model_id
        # Resolved for real in load(); kept as requested until then so a caller
        # reading .device before load() sees what it asked for.
        self.device = device
        self.backend: Optional[str] = None   # "torch" | "openvino", set by load()
        self._model = None
        self._processor = None
        self._dtype = None                   # torch backend only
        self._labels: Optional[list[str]] = None  # index 0 is always the positive

    @staticmethod
    def import_error(device: str = "AUTO") -> Optional[str]:
        """None if the CLIP stack for `device` imports cleanly, else a string
        naming the specific module that failed and the underlying exception.

        available() only says yes/no, which is useless in the windowed exe where
        the traceback is invisible. This catches *any* Exception (not just
        ImportError) so frozen-build failures show up verbatim — e.g. a missing
        dependency's metadata (PackageNotFoundError, a subclass of ImportError)
        or 'could not get source code' from a decorator's inspect.getsource.

        Only the backend that would actually be used is checked, so a CUDA-only
        install without optimum-intel isn't told CLIP is unavailable."""
        backend, resolved = resolve_device(device)
        if backend != "torch":
            mods = ("optimum.intel",)
        elif _is_directml(resolved):
            # torch alone is not enough on this path: importing torch_directml
            # is what registers the backend, so without it the resolved device
            # string is one torch will reject.
            mods = ("torch", "torch_directml")
        else:
            mods = ("torch",)
        mods = mods + ("transformers", "PIL")
        for mod in mods:
            try:
                __import__(mod)
            except Exception as e:  # noqa: BLE001 — report anything, not just ImportError
                return f"{mod} import failed: {type(e).__name__}: {e}"
        return None

    @staticmethod
    def available(device: str = "AUTO") -> bool:
        """True if the CLIP stack for `device` is importable."""
        return ClipFramePrefilter.import_error(device) is None

    def load(self):
        """Load CLIP on the best device for what this machine has, falling back
        a step at a time (CUDA -> Intel GPU -> CPU) so a missing GPU never
        breaks search outright."""
        backend, device = resolve_device(self.device)
        if backend == "torch" and self._load_torch(device):
            return
        self._load_openvino("GPU" if backend == "torch" else device)

    def _load_torch(self, device: str) -> bool:
        """Load CLIP on an NVIDIA or DirectML GPU via torch. True on success;
        False means the caller should fall back to OpenVINO (rather than lose
        search over, say, a GPU that's out of memory).

        Unlike the OpenVINO path this needs the *torch* weights, which are not
        in the bundled IR — so a first run fetches them to the HF cache. Offline,
        that fetch fails and we fall back, which is why nothing here is fatal.
        """
        import torch

        print(f"🔧 CLIP source: torch weights {self.model_id} -> "
              f"{device} ({_device_name(device)})")
        t0 = time.perf_counter()
        try:
            # Imported inside the try with everything else: in a frozen exe an
            # import here can fail on its own (see this module's docstring), and
            # that must cost us the GPU, not the search.
            from transformers import CLIPModel, CLIPProcessor

            # fp16 unconditionally, and it costs nothing that survives to the
            # index: embeddings are L2-normalised in fp32 afterwards and stored
            # as fp16 either way (measured agreement with fp32: 0.999997).
            #
            # Not obvious for pre-Volta cards, which have no Tensor Cores and
            # run *native* fp16 arithmetic at a fraction of fp32 — the reason to
            # expect fp16 to lose there. Measured on a GTX 1060 (sm_61) it wins
            # by 14% anyway: torch keeps fp32 accumulation for fp16 GEMMs, so
            # the ALU penalty never applies, while ViT-B/32 at these batch sizes
            # is bandwidth-bound and fp16 halves the traffic. Don't "fix" this
            # to a capability check without measuring on the card in question.
            dtype = torch.float16

            if _is_directml(device):
                from modules.system import directml_device as dml

                # Registering the backend. `import torch_directml` is what
                # teaches torch what "privateuseone" means; without it the
                # .to() below raises, and the string alone gives no hint why.
                if not dml.ensure_backend(device):
                    raise RuntimeError(
                        f"DirectML device {device!r} is no longer available: "
                        f"{dml.unavailable_reason()}")
                import torch_directml  # noqa: F401 — imported for the side effect

                # fp32 unless the user opted in. The paragraph above measured
                # fp16 on CUDA; DirectML is a different backend with uneven
                # half-precision coverage per operator, and a layer that falls
                # back converts on every call instead of saving bandwidth.
                # ViT-B/32 in fp32 is ~600 MB, which fits the cards this path
                # exists for.
                if not dml.prefer_float16():
                    dtype = torch.float32

            model = CLIPModel.from_pretrained(self.model_id, torch_dtype=dtype)
            self._model = model.to(device).eval()
            # The OV export dir carries the processor files, so prefer it and
            # keep the tokenizer/image config off the network.
            self._processor = CLIPProcessor.from_pretrained(_bundled_ov_dir() or self.model_id)
        except Exception as e:  # noqa: BLE001 — OOM, no driver, no network, bad build
            print(f"⚠️  CLIP load on {device} failed ({type(e).__name__}: {e}); "
                  f"trying OpenVINO.")
            self._model = self._processor = None
            return False

        self.backend, self.device, self._dtype = "torch", device, dtype
        print(f"✅ CLIP prefilter ready on {device} "
              f"(torch {str(dtype).replace('torch.', '')}, "
              f"{time.perf_counter() - t0:.1f}s, {self.model_id})")
        return True

    def _load_openvino(self, device: str):
        from optimum.intel import OVModelForZeroShotImageClassification
        from transformers import CLIPProcessor

        # Prefer a pre-converted IR (works in a frozen exe); fall back to a
        # runtime export from the HF id only when running from source.
        ov_dir = _bundled_ov_dir()
        src = ov_dir or self.model_id
        export = ov_dir is None

        # In a frozen exe a runtime export (export=True) traces the PyTorch model
        # via inspect.getsource, which fails with "could not get source code"
        # because .py sources aren't shipped. If we got here frozen with no IR,
        # the build didn't bundle it — fail loudly with an actionable message
        # instead of letting the export raise that cryptic error.
        if export and getattr(sys, "frozen", False):
            raise RuntimeError(
                "Pre-converted CLIP model is missing from this build "
                f"(looked for models/{BUNDLED_OV_DIRNAME}/openvino_model.xml in: "
                f"{_ov_dir_candidates()}). Rebuild with the "
                "'Pre-convert CLIP to OpenVINO IR' step, or drop the exported "
                f"folder next to the executable as models/{BUNDLED_OV_DIRNAME}."
            )
        print(f"🔧 CLIP source: {'bundled IR ' + ov_dir if ov_dir else 'runtime export ' + src}")

        t0 = time.perf_counter()
        try:
            self._model = OVModelForZeroShotImageClassification.from_pretrained(
                src, export=export, device=device,
            )
        except Exception as e:
            print(f"⚠️  CLIP load on device={device} failed ({e}); using CPU.")
            device = "CPU"
            self._model = OVModelForZeroShotImageClassification.from_pretrained(
                src, export=export, device="CPU",
            )
        self._processor = CLIPProcessor.from_pretrained(src)
        self.backend, self.device = "openvino", device
        print(f"✅ CLIP prefilter ready on {device} (OpenVINO, "
              f"{time.perf_counter() - t0:.1f}s, {'bundled IR' if ov_dir else self.model_id})")

    def set_query(self, target: str,
                  positive_template: str = "a photo of {}",
                  negatives: Optional[list[str]] = None):
        """Define what we're searching for. Index 0 of self._labels is the
        positive prompt; the rest are contrastive negatives for calibration."""
        positive = positive_template.format(target.strip())
        negs = list(negatives) if negatives else list(self.DEFAULT_NEGATIVES)
        self._labels = [positive] + negs

    def is_ready(self) -> bool:
        return self._model is not None and self._labels is not None

    def infer(self, texts, images):
        """One forward pass -> the model's output object (logits_per_image,
        image_embeds, text_embeds), whichever backend is loaded.

        The single place that knows a backend's calling convention, so callers
        (and ClipEmbedder) stay backend-agnostic.
        """
        inputs = self._processor(
            text=list(texts), images=list(images), return_tensors="pt", padding=True,
        )
        if self.backend != "torch":
            return self._model(**inputs)

        import torch

        # Move to the GPU, and match the model's fp16: the processor emits fp32
        # pixel_values, which a half model rejects outright. Integer tensors
        # (input_ids, attention_mask) must keep their dtype, hence the split.
        inputs = {
            k: (v.to(self.device, dtype=self._dtype) if v.is_floating_point()
                else v.to(self.device))
            for k, v in inputs.items()
        }
        with torch.inference_mode():
            return self._model(**inputs)

    def score_frames_bgr(self, frames_bgr: list) -> list[float]:
        """Return P(positive) in [0,1] for each BGR frame. Batched in one call."""
        import cv2
        from PIL import Image

        if not self.is_ready():
            raise RuntimeError("Call load() and set_query() before scoring.")

        images = [Image.fromarray(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))
                  for f in frames_bgr]
        outputs = self.infer(self._labels, images)
        # logits_per_image: [n_images, n_labels]; softmax → prob over labels.
        # .float() first: CLIP scales logits by ~100, and fp16 has ~3 decimal
        # digits up there, so the half softmax quantises scores the caller
        # thresholds on. Free on the OpenVINO backend, already fp32.
        probs = outputs.logits_per_image.float().softmax(dim=1)
        return [float(row[0]) for row in probs]  # column 0 = positive prompt

    def score_frame_bgr(self, frame_bgr) -> float:
        return self.score_frames_bgr([frame_bgr])[0]


# ---------------------------------------------------------------------------
# Standalone scan: rank a whole video and print the top-K timestamps.
# ---------------------------------------------------------------------------
def scan_video(video_path: str, query: str, interval: float = 1.0,
               topk: int = 30, batch: int = 16, device: str = "AUTO",
               start: float = 0.0, negatives: Optional[list[str]] = None):
    import cv2

    pf = ClipFramePrefilter(device=device)
    pf.load()
    pf.set_query(query, negatives=negatives)
    print(f"🔍 Query: '{query}'  (positive prompt: '{pf._labels[0]}')")
    print(f"   negatives: {pf._labels[1:]}")

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"❌ Could not open video: {video_path}")
        return []
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration = total / fps if fps else 0
    step = max(1, int(round(fps * interval)))
    start_frame = int(round(start * fps))
    print(f"📹 {video_path}")
    print(f"   {duration/60:.1f} min, {fps:.1f} fps, sampling every {interval}s "
          f"(~{max(0, (total - start_frame)) // step} frames)")

    results = []          # (timestamp, score)
    buf_frames, buf_ts = [], []
    t_scan0 = time.perf_counter()
    n_scored = 0
    idx = 0
    # grab() skips decode (cheap); retrieve() decodes only sampled frames.
    while True:
        if not cap.grab():
            break
        if idx >= start_frame and (idx - start_frame) % step == 0:
            ok, frame = cap.retrieve()
            if ok:
                buf_frames.append(frame)
                buf_ts.append(idx / fps)
                if len(buf_frames) >= batch:
                    for ts, sc in zip(buf_ts, pf.score_frames_bgr(buf_frames)):
                        results.append((ts, sc))
                    n_scored += len(buf_frames)
                    buf_frames, buf_ts = [], []
        idx += 1
    if buf_frames:
        for ts, sc in zip(buf_ts, pf.score_frames_bgr(buf_frames)):
            results.append((ts, sc))
        n_scored += len(buf_frames)
    cap.release()

    elapsed = time.perf_counter() - t_scan0
    per = (elapsed / n_scored * 1000) if n_scored else 0
    print(f"\n⏱  Scanned {n_scored} frames in {elapsed:.1f}s "
          f"({per:.1f} ms/frame incl. decode) on {pf.device}")

    results.sort(key=lambda x: -x[1])
    print(f"\n--- top {min(topk, len(results))} candidate timestamps ---")
    for ts, sc in results[:topk]:
        print(f"   {int(ts)//60:>3d}:{int(ts)%60:02d}  ({ts:7.1f}s)   score={sc:.3f}")
    return results


def main():
    import argparse
    ap = argparse.ArgumentParser(description="CLIP 预筛选——按查询对视频帧排序")
    ap.add_argument("--video", required=True)
    ap.add_argument("--query", required=True)
    ap.add_argument("--interval", type=float, default=1.0)
    ap.add_argument("--topk", type=int, default=30)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--device", default="AUTO",
                    help="AUTO/GPU（有 NVIDIA 时优先使用，否则 Intel GPU，再否则 CPU），"
                         "也可使用 CUDA、cuda:N、CPU 或任意 OpenVINO 设备字符串")
    ap.add_argument("--start", type=float, default=0.0)
    ap.add_argument("--negatives", default=None,
                    help="用逗号分隔的对比负样本。描述视频中的其他内容，"
                         "帮助 CLIP 区分目标动作，例如 "
                         "\"a closeup of a face,two people talking,a solo scene\"")
    args = ap.parse_args()

    negatives = None
    if args.negatives:
        negatives = [s.strip() for s in args.negatives.split(",") if s.strip()]

    reason = ClipFramePrefilter.import_error(args.device)
    if reason is not None:
        print(f"❌ CLIP unavailable — {reason}")
        print('   pip install "optimum[openvino]" pillow opencv-python  (Intel/CPU)')
        print("   ...or a CUDA torch build from pytorch.org  (NVIDIA)")
        return 1
    scan_video(args.video, args.query, interval=args.interval, topk=args.topk,
               batch=args.batch, device=args.device, start=args.start,
               negatives=negatives)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
